[package]
name = "DSRust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.6.0"
crossbeam-utils = "0.8.6"
crossbeam-queue = "0.3.3"